name: 단위 테스트 실행 및 Coverage Report 생성
run-name: 작업 브랜치 ${{ github.head_ref }} 로부터 ${{ github.base_ref }} 브랜치로 pull request 및 단위 테스트 및 Coverage Report 생성

on:
  pull_request:
    branches:
      - main

jobs:
  generate-coverage-reports:
    runs-on: ubuntu-latest
    steps:
      - name: 소스코드 Checkout
        uses: actions/checkout@v3
      - name: google-services.json 파일 생성
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo "$GOOGLE_SERVICES"
          echo "$GOOGLE_SERVICES" > composeApp/google-services.json
          cat composeApp/google-services.json
      - name: java 설치
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: 17
      - name: 테스트 코드 실행.
        shell: bash
        run: |
          ./gradlew clean koverHtmlReport
#      - name: 테스트 리포트 생성
#        uses: actions/upload-artifact@v4
#        with:
#          name: kover-report
#          path: app/build/reports/kover/html
#          retention-days: 1